#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Yamato Trading Platform

set -e

echo "========================================"
echo "Starting Yamato Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Paths
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$PROJECT_DIR/server"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${BLUE}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}✗ $name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}✓ $name ready on port $port${NC}"
}

# ============================================
# BACKEND SERVICE
# ============================================

echo ""
echo -e "${BLUE}Starting Backend (Node.js/Express)...${NC}"
cd "$BACKEND_DIR"

# Check dependencies
if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    npm install
fi

# Start backend server
npm start > /tmp/backend.log 2>&1 &
BACKEND_PID=$!
echo "Backend PID: $BACKEND_PID"

# Wait for backend to be ready
wait_for_service 3000 "Backend (HTTP:3000)" || {
    echo -e "${RED}Backend failed to start. Check /tmp/backend.log:${NC}"
    tail -20 /tmp/backend.log
    exit 1
}

# ============================================
# SUMMARY
# ============================================

echo ""
echo -e "${GREEN}========================================"
echo "✓ Development Environment Ready!"
echo "========================================${NC}"
echo ""
echo -e "${BLUE}Services:${NC}"
echo "  Backend:  ${GREEN}http://localhost:3000${NC}"
echo "  HTTPS:    ${GREEN}https://localhost:3443${NC}"
echo ""
echo -e "${BLUE}Open your browser:${NC}"
echo "  http://localhost:3000"
echo ""
echo -e "${BLUE}To stop services:${NC}"
echo "  Press Ctrl+C or kill $BACKEND_PID"
echo ""

# Keep script running
wait
